apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    name: myapp-rc
spec:
  template:
    metadata:
      name: httpdpod
      labels:
        env: production
    spec:
      containers:
      - name: httpd
        image: httpd:latest
  replicas: 2
        