apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    app: myapp
  
spec:
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: httpdpod
      labels:
        env: production
    spec:
      containers:
      - name: httpd
        image: httpd:latest
  replicas: 2